### PR TITLE
Use real package names instead of aliases from nixpkgs

### PR DESCRIPTION
**Pull request by ReplayCoding**
This makes it possible to use the overlay on NixOS systems where `nixpkgs.config.allowAliases = false`.

### CODE REVIEW

**Comment by colemickens** [comment]
selfishly, for my knowledge, can you give me a bit of background? Why is this so desirable to you?

(not opposed to it, and surprised at the size of the diff!)

**Comment by ReplayCoding** [comment]
When nixpkgs is configured to disallow aliases, NixOS rebuilds will fail with the following error:
```
error: anonymous function at /nix/store/...-source/pkgs/cage/default.nix:1:1 called without required argument 'pkgconfig'
```
This is because pkgconfig is defined pkgs/top-level/aliases.nix, which is not imported when `allowAliases = false`.

Regarding the large diff, I just ran sed on the repo, which made these changes.

**Comment by colemickens** [comment]
The diff size is fine, I was just curious what the overall goal was, but I guess it's just to stay fresh and avoid stale aliases. I'll pull and test this and merge it in the next few days.

**Review by colemickens — APPROVED** [review]
Looks okay. There's a "bad" diff in wayfire but it looks like it's an unused meson option anyway.

**Comment by colemickens** [comment]
My fault for merging, but this doesn't build...

**Comment by colemickens** [comment]
Looks like there was a new alias added, I fixed it up.

**Pull request merged**
