### PR TITLE
foot: init at 55c5f0590e487825431ca9c87fa68100f87358d1

### LINKED ISSUE #306: pkg request: foot - "A fast, lightweight and minimalistic Wayland terminal emulator"
https://codeberg.org/dnkl/foot

### PR DESCRIPTION
**Pull request by ReplayCoding**
Closes #306

### CODE REVIEW

**Comment by colemickens** [comment]
Is this the same as the nixpkgs derivation, other than the metadata plumbming?

**Comment by ReplayCoding** [comment]
Yes, I would have used an override, but the PGO stuff is hidden in a `let` expression, so it was just easier copy it.

**Comment by colemickens** [comment]
Thanks!

**Comment by ReplayCoding** [comment]
It looks like this broke the update script. This seems to be due to the output of `git ls-remote` having two lines instead of one:
```
55c5f0590e487825431ca9c87fa68100f87358d1	refs/heads/master
28131e9dc9a4b8b46e39c2e7ccac2b00f073dd45	refs/remotes/origin/master
```

**Comment by colemickens** [comment]
thanks, fixed: https://github.com/nix-community/nixpkgs-wayland/commit/f9ee75726e58aef32c5b7b7ce39013c47197fc45

**Pull request merged**
