### PR TITLE
 convert some packages to use githubTemplate 

### PR DESCRIPTION
**Pull request by Artturin**

### CODE REVIEW

**Comment by colemickens** [comment]
Somewhat related to this PR, are you following any other auto-updating discussions around the nix world? I hear there's some effort around it, but I don't know where/what exactly.

**Comment by colemickens** [comment]
Just skimming right now, does it make sense to expose some "api" for whether it's an "override" or a from-scratch package? Does it matter?

**Comment by Artturin** [comment]
> Just skimming right now, does it make sense to expose some "api" for whether it's an "override" or a from-scratch package? Does it matter?

I can't think of a reason why that would be needed atm

**Comment by colemickens** [comment]
>  +110 −411 

I like it.

**Comment by colemickens** [comment]
Along these lines, in my own nixcfg and the packages I "update" in there, I've used `passthru` to pass the metadata directly through the package itself. Just a random thought.

This is great though, definitely something on a miles-long-todo-list is checked off. Thanks!

**Comment by Artturin** [comment]
soon even less :) don't merge the pr but instead approve and I'll merge when ready

**Comment by Artturin** [comment]
soon even less :)

**Pull request merged**
