### PR TITLE
github-template: understand fetchSubmodules; fix gebaar-libinput

### LINKED ISSUE #364: `master` build is broken - but builds locally?
This is bizarre:

```
trying https://github.com/Osleg/gebaar-libinput-fork/archive/6ce14eb64a9f4bb8201bae26052521ae5e64f553.tar.gz
100 24180    0 24180    0     0   112k      0 --:--:-- --:--:-- --:--:--  112k
unpacking source archive /build/6ce14eb64a9f4bb8201bae26052521ae5e64f553.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/ip8l78731742l2r2zys0jzw9ayipgas7-source.drv':
         specified: sha256-NwF9TOJ6SzJJBa7mrUOCLEhz2xf0it7rVuOzhqvDwt0=
            got:    sha256-9l59FrRUWM6L5dnZm5X/ir/X+ZgzQ2TT5TnNeX1OyIw=
error: 1 dependencies of derivation '/nix/store/54slqk4q963pak3iqyqbar1wra54fkq1-gebaar-libinput-6ce14eb64a9f4bb8201bae26052521ae5e64f553.drv' failed to build
```

gebaar-libinput's source hasn't changed, rev hasn't changed, hash hasn't changed.

Did GitHub change something on their runner, and maybe gebaar-libinput exposes some FS quirk? (I think that's happened before with certain archives and macos targets for example)

### PR DESCRIPTION
**Pull request by colemickens**
Fixes #364

### CODE REVIEW

**Comment by colemickens** [comment]
Followups--->

gebaar-libinput overrides the source, but not the meta.homepage, which means our README links to the wrong place.

**Comment by colemickens** [comment]
Well, it will be after update.sh runs and updates the README...

**Comment by Artturin** [comment]
I'll add this in #360 thanks

**Comment by colemickens** [comment]
This is breaking my local build...

**Comment by colemickens** [comment]
maybe its not :/

**Pull request closed without merging**
